/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.moviebookingsystem;

/**
 *
 * @author Dell
 */
public class BookingConfirmation extends javax.swing.JFrame {

    /**
     * Creates new form BookingConfirmation
     */
    

    // Variables to store the data on this final screen
    
   public BookingConfirmation() {
    initComponents();
    lblBookingID.setText(DataStoreU.bookingId);
    lblMoviename.setText(DataStoreU.movieName);
    lblCinema.setText(DataStoreU.cinemaName);
    lblDate.setText(DataStoreU.date + " @ " + DataStoreU.showtime);
    lblDay.setText(DataStoreU.day);
    lblSelectesSeats.setText(DataStoreU.selectedSeats);
    lblAmountPaid.setText("Rs. " + DataStoreU.amountPaid);
    lblpaymethod.setText(DataStoreU.paymentMethod);
    
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblMoviename = new javax.swing.JLabel();
        lblCinema = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblDay = new javax.swing.JLabel();
        lblSelectesSeats = new javax.swing.JLabel();
        lblAmountPaid = new javax.swing.JLabel();
        lblpaymethod = new javax.swing.JLabel();
        lblBookingID = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(252, 216, 11));
        jLabel2.setText(".CineBook");

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(636, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(322, 322, 322)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(323, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel2)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jPanel3.setBackground(new java.awt.Color(50, 1, 75));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("*CineBook E-Ticket");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel3.setBackground(new java.awt.Color(227, 227, 227));
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Booking ID:");

        jLabel4.setForeground(new java.awt.Color(220, 220, 220));
        jLabel4.setText("-------------------------------------------------------------");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Movie:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Cinema:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Date&Time:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Day:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Seats:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Amount Paid:");

        jLabel11.setForeground(new java.awt.Color(167, 162, 162));
        jLabel11.setText("__________________________________________________________");

        jLabel12.setForeground(new java.awt.Color(178, 175, 175));
        jLabel12.setText("Payment:");

        lblMoviename.setText("Moviename");

        lblCinema.setText("Cinemaname");

        lblDate.setText("date&time");

        lblDay.setText("day");

        lblSelectesSeats.setText("selectedseats");

        lblAmountPaid.setText("amountpaid");

        lblpaymethod.setForeground(new java.awt.Color(204, 204, 204));
        lblpaymethod.setText("paymentmethod");

        lblBookingID.setForeground(new java.awt.Color(51, 51, 51));
        lblBookingID.setText("bookingID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblBookingID))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblpaymethod))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(110, 110, 110)
                                        .addComponent(lblAmountPaid)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMoviename)
                    .addComponent(lblCinema)
                    .addComponent(lblDate)
                    .addComponent(lblDay)
                    .addComponent(lblSelectesSeats))
                .addGap(119, 119, 119))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblBookingID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblMoviename))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblCinema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblDay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblSelectesSeats))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lblAmountPaid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblpaymethod))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(43, 1, 64));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 11, 11));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("< Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("My Booking");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(93, 220, 51));
        jLabel13.setText("*Booking Confirmed!");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel13))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel13)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // Ask user where to save
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    fileChooser.setDialogTitle("Save Your Ticket");
    fileChooser.setSelectedFile(new java.io.File(
        "CineBook_Ticket_" + DataStoreU.bookingId + ".pdf"));
    
    int userSelection = fileChooser.showSaveDialog(this);
    
    if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
        String filePath = fileChooser.getSelectedFile().getAbsolutePath();
        if (!filePath.endsWith(".pdf")) {
            filePath += ".pdf";
        }
        generateTicketPDF(filePath);
    }
}

private void generateTicketPDF(String filePath) {
    try {
        // Ticket size
        com.itextpdf.text.Rectangle ticketSize =
            new com.itextpdf.text.Rectangle(400, 650);
        
        com.itextpdf.text.Document document =
            new com.itextpdf.text.Document(ticketSize, 25, 25, 25, 25);
        
        com.itextpdf.text.pdf.PdfWriter.getInstance(
            document,
            new java.io.FileOutputStream(filePath));
        
        document.open();
        
        // ===== FONTS =====
        com.itextpdf.text.Font fontWhiteBig =
            new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 24,
                com.itextpdf.text.Font.BOLD,
                com.itextpdf.text.BaseColor.WHITE);
        
        com.itextpdf.text.Font fontWhiteSmall =
            new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 10,
                com.itextpdf.text.Font.NORMAL,
                new com.itextpdf.text.BaseColor(200, 200, 240));
        
        com.itextpdf.text.Font fontGreen =
            new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 14,
                com.itextpdf.text.Font.BOLD,
                new com.itextpdf.text.BaseColor(0, 160, 0));
        
        com.itextpdf.text.Font fontLabel =
            new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 9,
                com.itextpdf.text.Font.NORMAL,
                new com.itextpdf.text.BaseColor(120, 120, 120));
        
        com.itextpdf.text.Font fontValue =
            new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 11,
                com.itextpdf.text.Font.BOLD,
                new com.itextpdf.text.BaseColor(20, 20, 20));
        
        com.itextpdf.text.Font fontAmount =
            new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 18,
                com.itextpdf.text.Font.BOLD,
                new com.itextpdf.text.BaseColor(30, 30, 80));
        
        com.itextpdf.text.Font fontFooter =
            new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 8,
                com.itextpdf.text.Font.ITALIC,
                new com.itextpdf.text.BaseColor(150, 150, 150));
        
        com.itextpdf.text.Font fontBookingId =
            new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 12,
                com.itextpdf.text.Font.BOLD,
                new com.itextpdf.text.BaseColor(30, 30, 80));
        
        // ===== DARK HEADER =====
        com.itextpdf.text.pdf.PdfPTable header =
            new com.itextpdf.text.pdf.PdfPTable(1);
        header.setWidthPercentage(100);
        
        com.itextpdf.text.pdf.PdfPCell headerCell =
            new com.itextpdf.text.pdf.PdfPCell();
        headerCell.setBackgroundColor(
            new com.itextpdf.text.BaseColor(30, 30, 80));
        headerCell.setPadding(18);
        headerCell.setBorder(0);
        headerCell.setHorizontalAlignment(
            com.itextpdf.text.Element.ALIGN_CENTER);
        
        com.itextpdf.text.Paragraph appName =
            new com.itextpdf.text.Paragraph(".CineBook", fontWhiteBig);
        appName.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
        headerCell.addElement(appName);
        
        com.itextpdf.text.Paragraph eTicket =
            new com.itextpdf.text.Paragraph(
                "E - T I C K E T", fontWhiteSmall);
        eTicket.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
        headerCell.addElement(eTicket);
        
        header.addCell(headerCell);
        document.add(header);
        
        // ===== CONFIRMED =====
        com.itextpdf.text.Paragraph confirmed =
            new com.itextpdf.text.Paragraph(
                "\n✔️  Booking Confirmed!\n", fontGreen);
        confirmed.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
        document.add(confirmed);
        
        // ===== DIVIDER =====
        com.itextpdf.text.Paragraph div1 =
            new com.itextpdf.text.Paragraph(
                "- - - - - - - - - - - - - - - - - - - - - -\n",
                fontLabel);
        div1.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
        document.add(div1);
        
        // ===== BOOKING ID =====
        com.itextpdf.text.Paragraph bookingIdLabel =
            new com.itextpdf.text.Paragraph("BOOKING ID", fontLabel);
        bookingIdLabel.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
        document.add(bookingIdLabel);
        
        com.itextpdf.text.Paragraph bookingIdValue =
            new com.itextpdf.text.Paragraph(
                DataStoreU.bookingId, fontBookingId);
        bookingIdValue.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
        document.add(bookingIdValue);
        
        // ===== DIVIDER =====
        com.itextpdf.text.Paragraph div2 =
            new com.itextpdf.text.Paragraph(
                "\n- - - - - - - - - - - - - - - - - - - - - -\n",
                fontLabel);
        div2.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
        document.add(div2);
        
        // ===== DETAILS TABLE =====
        com.itextpdf.text.pdf.PdfPTable details =
            new com.itextpdf.text.pdf.PdfPTable(2);
        details.setWidthPercentage(90);
        details.setWidths(new float[]{1f, 1.8f});
        details.setSpacingBefore(5);
        
        addRow(details, "MOVIE",
            DataStoreU.movieName, fontLabel, fontValue);
        addRow(details, "CINEMA",
            DataStoreU.cinemaName, fontLabel, fontValue);
        addRow(details, "DATE",
            DataStoreU.date, fontLabel, fontValue);
        addRow(details, "DAY",
            DataStoreU.day, fontLabel, fontValue);
        addRow(details, "SHOWTIME",
            DataStoreU.showtime, fontLabel, fontValue);
        addRow(details, "SEATS",
            DataStoreU.selectedSeats, fontLabel, fontValue);
        addRow(details, "PAYMENT",
            DataStoreU.paymentMethod, fontLabel, fontValue);
        
        document.add(details);
        
        // ===== DIVIDER =====
        com.itextpdf.text.Paragraph div3 =
            new com.itextpdf.text.Paragraph(
                "\n- - - - - - - - - - - - - - - - - - - - - -",
                fontLabel);
        div3.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
        document.add(div3);
        
        // ===== AMOUNT =====
        com.itextpdf.text.Paragraph amountLabel =
            new com.itextpdf.text.Paragraph(
                "\nTOTAL AMOUNT PAID", fontLabel);
        amountLabel.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
        document.add(amountLabel);
        
        com.itextpdf.text.Paragraph amountValue =
            new com.itextpdf.text.Paragraph(
                "Rs. " + DataStoreU.amountPaid, fontAmount);
        amountValue.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
        document.add(amountValue);
        
        // ===== DIVIDER =====
        com.itextpdf.text.Paragraph div4 =
            new com.itextpdf.text.Paragraph(
                "\n- - - - - - - - - - - - - - - - - - - - - -\n",
                fontLabel);
        div4.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
        document.add(div4);
        
        // ===== FOOTER =====
        com.itextpdf.text.Paragraph footer =
            new com.itextpdf.text.Paragraph(
                "Thank you for booking with .CineBook\n" +
                "Please show this ticket at the cinema entrance.\n" +
                "Enjoy your movie! 🎬",
                fontFooter);
        footer.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
        document.add(footer);
        
        document.close();
        
        // ===== SUCCESS =====
        javax.swing.JOptionPane.showMessageDialog(this,
            "Ticket saved successfully!\n" + filePath,
            "Ticket Saved!",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        // ===== AUTO OPEN PDF =====
        java.awt.Desktop.getDesktop().open(
            new java.io.File(filePath));
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}

// ===== HELPER METHOD =====
private void addRow(
        com.itextpdf.text.pdf.PdfPTable table,
        String label, String value,
        com.itextpdf.text.Font labelFont,
        com.itextpdf.text.Font valueFont) {
    
    com.itextpdf.text.pdf.PdfPCell labelCell =
        new com.itextpdf.text.pdf.PdfPCell(
            new com.itextpdf.text.Phrase(label, labelFont));
    labelCell.setBorder(0);
    labelCell.setPaddingBottom(10);
    labelCell.setPaddingLeft(15);
    
    com.itextpdf.text.pdf.PdfPCell valueCell =
        new com.itextpdf.text.pdf.PdfPCell(
            new com.itextpdf.text.Phrase(value, valueFont));
    valueCell.setBorder(0);
    valueCell.setPaddingBottom(10);
    
    table.addCell(labelCell);
    table.addCell(valueCell);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new BookingHistory().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     new HomeScreen().setVisible(true);
    
    
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new BookingConfirmation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAmountPaid;
    private javax.swing.JLabel lblBookingID;
    private javax.swing.JLabel lblCinema;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblMoviename;
    private javax.swing.JLabel lblSelectesSeats;
    private javax.swing.JLabel lblpaymethod;
    // End of variables declaration//GEN-END:variables
}
