/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.moviebookingsystem;

import java.awt.Color;

/**
 *
 * @author Dell
 */
public class DateShowtimeScreen5 extends javax.swing.JFrame {
    String date = "";
    String time = "";

    /**
     * Creates new form DateShowtimeScreen5
     */
    public DateShowtimeScreen5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateGroup = new javax.swing.ButtonGroup();
        timeGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnMon5 = new javax.swing.JToggleButton();
        btnTue6 = new javax.swing.JToggleButton();
        btnWed7 = new javax.swing.JToggleButton();
        btnThu8 = new javax.swing.JToggleButton();
        btnFri9 = new javax.swing.JToggleButton();
        btnSat10 = new javax.swing.JToggleButton();
        btnSun11 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        btn100AM = new javax.swing.JToggleButton();
        btn130PM = new javax.swing.JToggleButton();
        btn430PM = new javax.swing.JToggleButton();
        btn730PM = new javax.swing.JToggleButton();
        btn1030PM = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        lblSelection = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(252, 216, 11));
        jLabel2.setText(".CineBook");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(322, 322, 322)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(323, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel2)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(228, 224, 224));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Step 2 of 5 __ Choose Date & Time");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(63, 63, 63))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Next ->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setText("<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Select Date");

        dateGroup.add(btnMon5);
        btnMon5.setText("Mon 11");
        btnMon5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMon5ActionPerformed(evt);
            }
        });

        dateGroup.add(btnTue6);
        btnTue6.setText("Tue 12");
        btnTue6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTue6ActionPerformed(evt);
            }
        });

        dateGroup.add(btnWed7);
        btnWed7.setText("Wed 13");
        btnWed7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWed7ActionPerformed(evt);
            }
        });

        dateGroup.add(btnThu8);
        btnThu8.setText("Thu 14");
        btnThu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThu8ActionPerformed(evt);
            }
        });

        dateGroup.add(btnFri9);
        btnFri9.setText("Fri 15");
        btnFri9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFri9ActionPerformed(evt);
            }
        });

        dateGroup.add(btnSat10);
        btnSat10.setText("Sat 16");
        btnSat10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSat10ActionPerformed(evt);
            }
        });

        dateGroup.add(btnSun11);
        btnSun11.setText("Sun 17");
        btnSun11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSun11ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Select Showtime");

        timeGroup.add(btn100AM);
        btn100AM.setText("10:00 AM");
        btn100AM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100AMActionPerformed(evt);
            }
        });

        timeGroup.add(btn130PM);
        btn130PM.setText("1:30 PM");
        btn130PM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn130PMActionPerformed(evt);
            }
        });

        timeGroup.add(btn430PM);
        btn430PM.setText("4:30 PM");
        btn430PM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn430PMActionPerformed(evt);
            }
        });

        timeGroup.add(btn730PM);
        btn730PM.setText("7:30 PM");
        btn730PM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn730PMActionPerformed(evt);
            }
        });

        timeGroup.add(btn1030PM);
        btn1030PM.setText("10:30 PM");
        btn1030PM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1030PMActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(252, 245, 173));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 1, true));

        lblSelection.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSelection.setText("Selected:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblSelection)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelection)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnMon5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSat10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnTue6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnWed7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnThu8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnFri9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnSun11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn100AM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn730PM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btn130PM, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn430PM, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn1030PM, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMon5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTue6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWed7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThu8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFri9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSun11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSat10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn100AM)
                    .addComponent(btn130PM)
                    .addComponent(btn430PM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1030PM)
                    .addComponent(btn730PM))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(847, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThu8ActionPerformed
   DataStoreU.day = "Thursday";
    DataStoreU.date = "14";
        updateFinalSelection();        // TODO add your handling code here:
    }//GEN-LAST:event_btnThu8ActionPerformed

    private void btnFri9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFri9ActionPerformed
     DataStoreU.day = "Friday";
    DataStoreU.date = "15";
        updateFinalSelection();  
 if (btnFri9.isSelected()) {
    btnFri9.setBackground(Color.RED);
    btnFri9.setForeground(Color.WHITE);
} else {
    btnFri9.setBackground(Color.LIGHT_GRAY);
    btnFri9.setForeground(Color.BLACK);
} // TODO add your handling code here:
    }//GEN-LAST:event_btnFri9ActionPerformed

    private void btn730PMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn730PMActionPerformed
     DataStoreU.showtime = "7:30 PM";
        updateFinalSelection();        // TODO add your handling code here:
    }//GEN-LAST:event_btn730PMActionPerformed

    private void btnMon5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMon5ActionPerformed
     DataStoreU.day = "Monday";
    DataStoreU.date = "11";    
        updateFinalSelection();        // TODO add your handling code here:
    }//GEN-LAST:event_btnMon5ActionPerformed

    private void btn100AMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100AMActionPerformed
     DataStoreU.showtime = "10:00 AM";
        updateFinalSelection();        // TODO add your handling code here:
    }//GEN-LAST:event_btn100AMActionPerformed

    private void btnTue6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTue6ActionPerformed
    DataStoreU.day = "Tuesday";
    DataStoreU.date = "12";
        updateFinalSelection();        // TODO add your handling code here:
    }//GEN-LAST:event_btnTue6ActionPerformed

    private void btnWed7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWed7ActionPerformed
    DataStoreU.day = "Wednesday";
    DataStoreU.date = "13";
        
     updateFinalSelection();        // TODO add your handling code here:
    }//GEN-LAST:event_btnWed7ActionPerformed

    private void btnSat10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSat10ActionPerformed
    DataStoreU.day = "Saturday";
    DataStoreU.date = "16";
        updateFinalSelection();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSat10ActionPerformed

    private void btnSun11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSun11ActionPerformed
    DataStoreU.day = "Sunday";
    DataStoreU.date = "17";
        updateFinalSelection();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSun11ActionPerformed

    private void btn130PMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn130PMActionPerformed
      DataStoreU.showtime = "1:30 PM";
        updateFinalSelection();        // TODO add your handling code here:
    }//GEN-LAST:event_btn130PMActionPerformed

    private void btn430PMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn430PMActionPerformed
      DataStoreU.showtime = "4:30 PM";
        updateFinalSelection();        // TODO add your handling code here:
    }//GEN-LAST:event_btn430PMActionPerformed

    private void btn1030PMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1030PMActionPerformed
      DataStoreU.showtime = "10:30 PM";
        updateFinalSelection();        // TODO add your handling code here:
    }//GEN-LAST:event_btn1030PMActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   new SeatSelectionScreen().setVisible(true);
this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   new HomeScreen().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
private void updateFinalSelection() {
   

    
    if (btnMon5.isSelected()) { date = "Monday 11"; setColor(btnMon5); } else { resetColor(btnMon5); }
    if (btnTue6.isSelected()) { date = "Tuesday 12"; setColor(btnTue6); } else { resetColor(btnTue6); }
    if (btnWed7.isSelected()) { date = "Wednesday 13"; setColor(btnWed7); } else { resetColor(btnWed7); }
    if (btnThu8.isSelected()) { date = "Thursday 14"; setColor(btnThu8); } else { resetColor(btnThu8); }
    if (btnFri9.isSelected()) { date = "Friday 15"; setColor(btnFri9); } else { resetColor(btnFri9); }
    if (btnSat10.isSelected()) { date = "Saturday 16"; setColor(btnSat10); } else { resetColor(btnSat10); }
    if (btnSun11.isSelected()) { date = "Sunday 17"; setColor(btnSun11); } else { resetColor(btnSun11); }

    
    if (btn100AM.isSelected()) { time = "10:00 AM"; setColor(btn100AM); } else { resetColor(btn100AM); }
    if (btn130PM.isSelected()) { time = "1:30 PM"; setColor(btn130PM); } else { resetColor(btn130PM); }
    if (btn430PM.isSelected()) { time = "4:30 PM"; setColor(btn430PM); } else { resetColor(btn430PM); }
    if (btn730PM.isSelected()) { time = "7:30 PM"; setColor(btn730PM); } else { resetColor(btn730PM); }
    if (btn1030PM.isSelected()) { time = "10:30 PM"; setColor(btn1030PM); } else { resetColor(btn1030PM); }

    // --- UPDATE THE LABEL ---
    lblSelection.setText("Selected: " + date + " | " + time);
}

// Helper methods to save space:
private void setColor(javax.swing.JToggleButton btn) {
    btn.setBackground(Color.RED);
    btn.setForeground(Color.WHITE);
}

private void resetColor(javax.swing.JToggleButton btn) {
    btn.setBackground(Color.WHITE);
    btn.setForeground(Color.BLACK);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DateShowtimeScreen5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DateShowtimeScreen5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DateShowtimeScreen5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DateShowtimeScreen5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DateShowtimeScreen5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn100AM;
    private javax.swing.JToggleButton btn1030PM;
    private javax.swing.JToggleButton btn130PM;
    private javax.swing.JToggleButton btn430PM;
    private javax.swing.JToggleButton btn730PM;
    private javax.swing.JToggleButton btnFri9;
    private javax.swing.JToggleButton btnMon5;
    private javax.swing.JToggleButton btnSat10;
    private javax.swing.JToggleButton btnSun11;
    private javax.swing.JToggleButton btnThu8;
    private javax.swing.JToggleButton btnTue6;
    private javax.swing.JToggleButton btnWed7;
    private javax.swing.ButtonGroup dateGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblSelection;
    private javax.swing.ButtonGroup timeGroup;
    // End of variables declaration//GEN-END:variables
}
